import CoreImage
import Foundation

enum ProfileCatalog {
    static let presets: [FilmLookProfile] = [
        make(
            id: "kodak-funsaver-800",
            name: "Kodak FunSaver 800",
            description: "Built from the Kodak FunSaver references: high contrast span, thick density grain, warm rolled highlights, and heavy plastic-lens edge falloff.",
            exposure: 0.03, contrast: 1.30, toe: 0.28, shoulder: 0.76, black: 0.024, white: 0.905,
            saturation: 0.94, vibrance: 0.12, temp: 260, tint: -4,
            lut: "kodak-funsaver-800", lutIntensity: 0.96,
            grain: grain(.disposableCompact, size: 2.12, roughness: 0.90, strength: 0.44, chroma: 0.18, bias: 0.42, shadows: 1.06, mids: 1.42, highlights: 1.12, resolution: 0.42),
            halation: halation(0.22, threshold: 0.72, radius: 18, tint: CIColor(red: 1.0, green: 0.40, blue: 0.10), blend: 0.54),
            bloom: bloom(0.14, threshold: 0.75, radius: 14, softness: 0.70, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.40, radius: 0.82, softness: 0.92),
            lens: LensProfile(enabled: true, chromaticAberration: 0.72, edgeSoftness: 0.76, compactBlur: 0.22),
            dust: DustProfile(enabled: true, dustAmount: 0.080, scratchAmount: 0.018, lightLeakAmount: 0.045),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.60, edgeHaloSuppression: 0.68, localHDRCompression: 0.36, preBlur: 0.22),
            print: PrintResponseProfile(highlightDesaturation: 0.58, highlightRolloff: 0.76, paperBlack: 0.018, paperWhite: 0.958),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.42, crossProcess: 0.26, cyanShadow: 0.08, warmHighlight: 0.52, redChannelBloom: 0.42, greenBias: -0.02, blueBias: -0.08, dyeContamination: 0.44, scanFade: 0.06, cheapness: 0.70),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.42, dustJitter: 0.56, dateStampJitter: 0, flashJitter: 0),
            flatness: flatness(0.16, frequency: 0.85),
            labScan: labScan(0.14, noise: 0.06)
        ),
        make(
            id: "kodak-funsaver-overexposed",
            name: "Kodak FunSaver Overexposed",
            description: "Built from the brighter Kodak frames: warm clipped highlights, strong rolloff, chunky grain, and the same rough disposable optics without a center flash circle.",
            exposure: 0.14, contrast: 1.16, toe: 0.34, shoulder: 0.84, black: 0.032, white: 0.895,
            saturation: 0.90, vibrance: 0.10, temp: 340, tint: -5,
            lut: "kodak-funsaver-800", lutIntensity: 0.88,
            grain: grain(.disposableCompact, size: 2.04, roughness: 0.86, strength: 0.38, chroma: 0.14, bias: 0.36, shadows: 0.90, mids: 1.28, highlights: 1.20, resolution: 0.46),
            halation: halation(0.18, threshold: 0.70, radius: 20, tint: CIColor(red: 1.0, green: 0.46, blue: 0.14), blend: 0.46),
            bloom: bloom(0.20, threshold: 0.68, radius: 20, softness: 0.82, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.34, radius: 0.86, softness: 0.94),
            lens: LensProfile(enabled: true, chromaticAberration: 0.62, edgeSoftness: 0.72, compactBlur: 0.20),
            dust: DustProfile(enabled: true, dustAmount: 0.070, scratchAmount: 0.014, lightLeakAmount: 0.060),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.58, edgeHaloSuppression: 0.66, localHDRCompression: 0.44, preBlur: 0.20),
            print: PrintResponseProfile(highlightDesaturation: 0.68, highlightRolloff: 0.84, paperBlack: 0.020, paperWhite: 0.950),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.34, crossProcess: 0.22, cyanShadow: 0.06, warmHighlight: 0.64, redChannelBloom: 0.50, greenBias: -0.03, blueBias: -0.10, dyeContamination: 0.40, scanFade: 0.12, cheapness: 0.64),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.50, dustJitter: 0.50, dateStampJitter: 0, flashJitter: 0),
            flatness: flatness(0.14, frequency: 0.90),
            labScan: labScan(0.12, noise: 0.05)
        ),
        make(
            id: "fuji-quicksnap-400",
            name: "Fuji QuickSnap 400",
            description: "Built from the Fuji QuickSnap set: bright cooler scans, lower saturation, cyan-green shadows, clean grain, and the strongest edge softness in the corpus.",
            exposure: 0.16, contrast: 0.98, toe: 0.38, shoulder: 0.60, black: 0.036, white: 0.940,
            saturation: 0.86, vibrance: 0.18, temp: -380, tint: -2,
            lut: "fuji-quicksnap-400", lutIntensity: 0.92,
            grain: grain(.medium250, size: 1.52, roughness: 0.58, strength: 0.22, chroma: 0.12, bias: 0.40, shadows: 0.78, mids: 1.02, highlights: 0.70, resolution: 0.56),
            halation: halation(0.09, threshold: 0.80, radius: 14, tint: CIColor(red: 1.0, green: 0.38, blue: 0.15), blend: 0.32),
            bloom: bloom(0.10, threshold: 0.79, radius: 13, softness: 0.68, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.26, radius: 0.90, softness: 0.92),
            lens: LensProfile(enabled: true, chromaticAberration: 0.58, edgeSoftness: 0.86, compactBlur: 0.18),
            dust: DustProfile(enabled: true, dustAmount: 0.045, scratchAmount: 0.010, lightLeakAmount: 0.020),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.50, edgeHaloSuppression: 0.60, localHDRCompression: 0.42, preBlur: 0.18),
            print: PrintResponseProfile(highlightDesaturation: 0.48, highlightRolloff: 0.64, paperBlack: 0.020, paperWhite: 0.988),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.22, crossProcess: 0.10, cyanShadow: 0.38, warmHighlight: 0.10, redChannelBloom: 0.04, greenBias: 0.12, blueBias: 0.20, dyeContamination: 0.22, scanFade: 0.16, cheapness: 0.38),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.24, dustJitter: 0.34, dateStampJitter: 0, flashJitter: 0),
            flatness: flatness(0.10, frequency: 0.95),
            labScan: labScan(0.10, noise: 0.03)
        ),
        make(
            id: "fuji-quicksnap-green",
            name: "Fuji QuickSnap Green",
            description: "A cooler Fuji variation from the greener QuickSnap references: brighter midtones, extra cyan shadows, low chroma, and plasticky edge blur.",
            exposure: 0.20, contrast: 0.90, toe: 0.42, shoulder: 0.66, black: 0.044, white: 0.950,
            saturation: 0.78, vibrance: 0.14, temp: -520, tint: -7,
            lut: "fuji-quicksnap-400", lutIntensity: 0.84,
            grain: grain(.medium250, size: 1.46, roughness: 0.52, strength: 0.18, chroma: 0.10, bias: 0.38, shadows: 0.70, mids: 0.92, highlights: 0.58, resolution: 0.60),
            halation: halation(0.06, threshold: 0.84, radius: 12, tint: CIColor(red: 1.0, green: 0.42, blue: 0.18), blend: 0.22),
            bloom: bloom(0.12, threshold: 0.76, radius: 16, softness: 0.76, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.20, radius: 0.98, softness: 0.90),
            lens: LensProfile(enabled: true, chromaticAberration: 0.46, edgeSoftness: 0.78, compactBlur: 0.16),
            dust: DustProfile(enabled: true, dustAmount: 0.030, scratchAmount: 0.006, lightLeakAmount: 0.015),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.46, edgeHaloSuppression: 0.56, localHDRCompression: 0.44, preBlur: 0.16),
            print: PrintResponseProfile(highlightDesaturation: 0.52, highlightRolloff: 0.66, paperBlack: 0.026, paperWhite: 0.990),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.12, crossProcess: 0.04, cyanShadow: 0.48, warmHighlight: 0.04, redChannelBloom: 0.02, greenBias: 0.22, blueBias: 0.16, dyeContamination: 0.18, scanFade: 0.24, cheapness: 0.28),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.16, dustJitter: 0.24, dateStampJitter: 0, flashJitter: 0)
        ),
        make(
            id: "huji-direct",
            name: "HUJI Direct",
            description: "Built from the direct HUJI exports with HUJI CAM EXIF: dark average exposure, high contrast, subdued saturation, orange date stamp, and aggressive phone-detail removal.",
            exposure: -0.10, contrast: 1.24, toe: 0.20, shoulder: 0.70, black: 0.028, white: 0.910,
            saturation: 1.04, vibrance: 0.30, temp: 320, tint: -8,
            lut: "huji-1998", lutIntensity: 0.96,
            grain: grain(.disposableCompact, size: 1.92, roughness: 0.84, strength: 0.36, chroma: 0.32, bias: 0.40, shadows: 1.00, mids: 1.36, highlights: 0.78, resolution: 0.46),
            halation: halation(0.28, threshold: 0.68, radius: 23, tint: CIColor(red: 1.0, green: 0.32, blue: 0.07), blend: 0.66),
            bloom: bloom(0.20, threshold: 0.70, radius: 21, softness: 0.84, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.38, radius: 0.82, softness: 0.94),
            lens: LensProfile(enabled: true, chromaticAberration: 0.94, edgeSoftness: 0.72, compactBlur: 0.24),
            dust: DustProfile(enabled: true, dustAmount: 0.100, scratchAmount: 0.028, lightLeakAmount: 0.22),
            stamp: DateStampProfile(enabled: true, text: DateFormatter.filmStamp.string(from: Date()), opacity: 0.92),
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.66, edgeHaloSuppression: 0.74, localHDRCompression: 0.50, preBlur: 0.24),
            print: PrintResponseProfile(highlightDesaturation: 0.56, highlightRolloff: 0.76, paperBlack: 0.020, paperWhite: 0.958),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.74, crossProcess: 0.54, cyanShadow: 0.18, warmHighlight: 0.66, redChannelBloom: 0.60, greenBias: -0.06, blueBias: -0.08, dyeContamination: 0.62, scanFade: 0.06, cheapness: 0.88),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 1.12, dustJitter: 0.84, dateStampJitter: 1.00, flashJitter: 0),
            flatness: flatness(0.22, frequency: 0.72),
            labScan: labScan(0.20, noise: 0.12)
        ),
        make(
            id: "huji-board-dark",
            name: "HUJI Board Dark",
            description: "Built from the darker HUJI board references: very low luma, heavy shadow pressure, strong contrast, crunchy mids, and unstable date-stamp energy.",
            exposure: -0.24, contrast: 1.34, toe: 0.16, shoulder: 0.74, black: 0.018, white: 0.900,
            saturation: 0.98, vibrance: 0.24, temp: 180, tint: -6,
            lut: "huji-1998", lutIntensity: 0.98,
            grain: grain(.disposableCompact, size: 2.16, roughness: 0.90, strength: 0.40, chroma: 0.28, bias: 0.52, shadows: 1.20, mids: 1.46, highlights: 0.70, resolution: 0.40),
            halation: halation(0.32, threshold: 0.66, radius: 26, tint: CIColor(red: 1.0, green: 0.30, blue: 0.06), blend: 0.74),
            bloom: bloom(0.22, threshold: 0.68, radius: 23, softness: 0.88, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.52, radius: 0.74, softness: 0.96),
            lens: LensProfile(enabled: true, chromaticAberration: 1.02, edgeSoftness: 0.82, compactBlur: 0.28),
            dust: DustProfile(enabled: true, dustAmount: 0.120, scratchAmount: 0.036, lightLeakAmount: 0.32),
            stamp: DateStampProfile(enabled: true, text: DateFormatter.filmStamp.string(from: Date()), opacity: 1.0),
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.70, edgeHaloSuppression: 0.78, localHDRCompression: 0.54, preBlur: 0.26),
            print: PrintResponseProfile(highlightDesaturation: 0.64, highlightRolloff: 0.82, paperBlack: 0.018, paperWhite: 0.944),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.84, crossProcess: 0.64, cyanShadow: 0.24, warmHighlight: 0.72, redChannelBloom: 0.72, greenBias: -0.08, blueBias: -0.12, dyeContamination: 0.70, scanFade: 0.02, cheapness: 0.98),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 1.48, dustJitter: 0.96, dateStampJitter: 1.16, flashJitter: 0),
            flatness: flatness(0.26, frequency: 0.66),
            labScan: labScan(0.24, noise: 0.15)
        ),
        make(
            id: "huji-light-leak",
            name: "HUJI Light Leak",
            description: "Built from the HUJI and imperfection leads: random orange-red side leaks, high cheapness, date stamp, clipped reds, and no artificial flash circle.",
            exposure: -0.04, contrast: 1.22, toe: 0.22, shoulder: 0.78, black: 0.030, white: 0.900,
            saturation: 1.12, vibrance: 0.38, temp: 420, tint: -10,
            lut: "huji-flash-leak", lutIntensity: 0.98,
            grain: grain(.disposableCompact, size: 2.10, roughness: 0.90, strength: 0.40, chroma: 0.38, bias: 0.40, shadows: 1.05, mids: 1.45, highlights: 0.82, resolution: 0.42),
            halation: halation(0.38, threshold: 0.66, radius: 28, tint: CIColor(red: 1.0, green: 0.30, blue: 0.06), blend: 0.78),
            bloom: bloom(0.26, threshold: 0.66, radius: 25, softness: 0.90, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.46, radius: 0.76, softness: 0.94),
            lens: LensProfile(enabled: true, chromaticAberration: 1.05, edgeSoftness: 0.80, compactBlur: 0.26),
            dust: DustProfile(enabled: true, dustAmount: 0.120, scratchAmount: 0.036, lightLeakAmount: 0.50),
            stamp: DateStampProfile(enabled: true, text: DateFormatter.filmStamp.string(from: Date()), opacity: 1.0),
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.68, edgeHaloSuppression: 0.76, localHDRCompression: 0.54, preBlur: 0.24),
            print: PrintResponseProfile(highlightDesaturation: 0.64, highlightRolloff: 0.82, paperBlack: 0.020, paperWhite: 0.948),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.86, crossProcess: 0.66, cyanShadow: 0.18, warmHighlight: 0.76, redChannelBloom: 0.78, greenBias: -0.08, blueBias: -0.12, dyeContamination: 0.72, scanFade: 0.04, cheapness: 1.00),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 1.60, dustJitter: 1.00, dateStampJitter: 1.20, flashJitter: 0)
        ),
        make(
            id: "dazz-organic",
            name: "Dazz Organic",
            description: "Built from the Autostraddle Dazz references: warmer and more saturated than the Dazz comparisons, with organic softness, gentle bloom, and visible but pleasant grain.",
            exposure: 0.02, contrast: 1.02, toe: 0.34, shoulder: 0.62, black: 0.040, white: 0.940,
            saturation: 1.04, vibrance: 0.28, temp: 260, tint: 2,
            lut: "dazz-classic", lutIntensity: 0.90,
            grain: grain(.medium250, size: 1.40, roughness: 0.62, strength: 0.22, chroma: 0.12, bias: 0.54, shadows: 0.78, mids: 1.06, highlights: 0.78, resolution: 0.68),
            halation: halation(0.16, threshold: 0.78, radius: 18, tint: CIColor(red: 1.0, green: 0.42, blue: 0.16), blend: 0.42),
            bloom: bloom(0.18, threshold: 0.72, radius: 23, softness: 0.90, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.18, radius: 1.02, softness: 0.88),
            lens: LensProfile(enabled: true, chromaticAberration: 0.32, edgeSoftness: 0.36, compactBlur: 0.08),
            dust: DustProfile(enabled: true, dustAmount: 0.045, scratchAmount: 0.010, lightLeakAmount: 0.055),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.42, edgeHaloSuppression: 0.46, localHDRCompression: 0.38, preBlur: 0.10),
            print: PrintResponseProfile(highlightDesaturation: 0.48, highlightRolloff: 0.62, paperBlack: 0.026, paperWhite: 0.982),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.30, crossProcess: 0.18, cyanShadow: 0.12, warmHighlight: 0.34, redChannelBloom: 0.18, greenBias: -0.02, blueBias: 0.00, dyeContamination: 0.30, scanFade: 0.20, cheapness: 0.16),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.38, dustJitter: 0.28, dateStampJitter: 0, flashJitter: 0)
        ),
        make(
            id: "dazz-d-exp",
            name: "Dazz D Exp",
            description: "Built from the Dazz comparison references: low-key exposure, firm shadows, punchier reds/blues, app-film contrast, and restrained defects.",
            exposure: -0.18, contrast: 1.30, toe: 0.24, shoulder: 0.52, black: 0.018, white: 0.952,
            saturation: 1.08, vibrance: 0.18, temp: 120, tint: -2,
            lut: "dazz-d-exp", lutIntensity: 0.94,
            grain: grain(.medium250, size: 1.12, roughness: 0.50, strength: 0.16, chroma: 0.10, bias: 0.54, shadows: 0.82, mids: 0.94, highlights: 0.64, resolution: 0.76),
            halation: halation(0.15, threshold: 0.78, radius: 15, tint: CIColor(red: 1.0, green: 0.32, blue: 0.09), blend: 0.40),
            bloom: bloom(0.10, threshold: 0.80, radius: 13, softness: 0.60, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.24, radius: 0.96, softness: 0.82),
            lens: LensProfile(enabled: true, chromaticAberration: 0.36, edgeSoftness: 0.30, compactBlur: 0.04),
            dust: DustProfile(enabled: true, dustAmount: 0.030, scratchAmount: 0.006, lightLeakAmount: 0.030),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.30, edgeHaloSuppression: 0.36, localHDRCompression: 0.18, preBlur: 0.04),
            print: PrintResponseProfile(highlightDesaturation: 0.24, highlightRolloff: 0.46, paperBlack: 0.008, paperWhite: 0.990),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.56, crossProcess: 0.36, cyanShadow: 0.18, warmHighlight: 0.30, redChannelBloom: 0.22, greenBias: 0.02, blueBias: 0.02, dyeContamination: 0.28, scanFade: -0.02, cheapness: 0.06),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.22, dustJitter: 0.18, dateStampJitter: 0, flashJitter: 0)
        ),
        make(
            id: "dazz-cpm35",
            name: "Dazz CPM35",
            description: "Built from the soft Dazz comparison references: low contrast, pastel scan fade, creamy highlight bloom, low grain, and minimal defects.",
            exposure: 0.10, contrast: 0.86, toe: 0.54, shoulder: 0.72, black: 0.060, white: 0.928,
            saturation: 0.82, vibrance: 0.18, temp: 150, tint: 4,
            lut: "dazz-cpm35", lutIntensity: 0.90,
            grain: grain(.fine50, size: 1.05, roughness: 0.38, strength: 0.09, chroma: 0.06, bias: 0.48, shadows: 0.54, mids: 0.74, highlights: 0.46, resolution: 0.84),
            halation: halation(0.08, threshold: 0.84, radius: 16, tint: CIColor(red: 1.0, green: 0.44, blue: 0.22), blend: 0.28),
            bloom: bloom(0.20, threshold: 0.68, radius: 26, softness: 0.94, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.10, radius: 1.18, softness: 0.86),
            lens: LensProfile(enabled: true, chromaticAberration: 0.16, edgeSoftness: 0.26, compactBlur: 0.08),
            dust: DustProfile(enabled: true, dustAmount: 0.018, scratchAmount: 0.003, lightLeakAmount: 0.012),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.46, edgeHaloSuppression: 0.40, localHDRCompression: 0.42, preBlur: 0.12),
            print: PrintResponseProfile(highlightDesaturation: 0.58, highlightRolloff: 0.70, paperBlack: 0.032, paperWhite: 0.986),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.12, crossProcess: 0.04, cyanShadow: 0.08, warmHighlight: 0.22, redChannelBloom: 0.06, greenBias: -0.03, blueBias: 0.02, dyeContamination: 0.12, scanFade: 0.34, cheapness: 0.02),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.10, dustJitter: 0.12, dateStampJitter: 0, flashJitter: 0)
        ),
        make(
            id: "dazz-night-market",
            name: "Dazz Night Market",
            description: "Built from the warmer/night Dazz organic references: dark luma, saturated warm color, stronger grain proxy, and soft bloom without flash circles.",
            exposure: -0.16, contrast: 1.12, toe: 0.30, shoulder: 0.66, black: 0.024, white: 0.930,
            saturation: 1.18, vibrance: 0.28, temp: 420, tint: -2,
            lut: "dazz-d-exp", lutIntensity: 0.86,
            grain: grain(.medium250, size: 1.46, roughness: 0.66, strength: 0.24, chroma: 0.16, bias: 0.60, shadows: 0.88, mids: 1.14, highlights: 0.86, resolution: 0.64),
            halation: halation(0.24, threshold: 0.70, radius: 24, tint: CIColor(red: 1.0, green: 0.32, blue: 0.07), blend: 0.60),
            bloom: bloom(0.20, threshold: 0.70, radius: 22, softness: 0.84, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.30, radius: 0.90, softness: 0.88),
            lens: LensProfile(enabled: true, chromaticAberration: 0.44, edgeSoftness: 0.42, compactBlur: 0.10),
            dust: DustProfile(enabled: true, dustAmount: 0.055, scratchAmount: 0.012, lightLeakAmount: 0.060),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.44, edgeHaloSuppression: 0.50, localHDRCompression: 0.34, preBlur: 0.10),
            print: PrintResponseProfile(highlightDesaturation: 0.42, highlightRolloff: 0.66, paperBlack: 0.018, paperWhite: 0.972),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.42, crossProcess: 0.30, cyanShadow: 0.18, warmHighlight: 0.52, redChannelBloom: 0.34, greenBias: -0.04, blueBias: -0.06, dyeContamination: 0.36, scanFade: 0.12, cheapness: 0.22),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.44, dustJitter: 0.30, dateStampJitter: 0, flashJitter: 0)
        ),
        make(
            id: "imperfect-lab-print",
            name: "Imperfect Lab Print",
            description: "Built from the film-issue and disposable-tip references: print fade, edge wear, intermittent leaks, dust, and warm imperfect lab processing.",
            exposure: 0.08, contrast: 0.86, toe: 0.64, shoulder: 0.66, black: 0.086, white: 0.895,
            saturation: 0.72, vibrance: 0.08, temp: 430, tint: -6,
            lut: "faded-lab-print", lutIntensity: 0.92,
            grain: grain(.fine50, size: 1.16, roughness: 0.56, strength: 0.14, chroma: 0.06, bias: 0.30, shadows: 0.58, mids: 0.90, highlights: 0.48, resolution: 0.62),
            halation: halation(0.06, threshold: 0.84, radius: 16, tint: CIColor(red: 1.0, green: 0.46, blue: 0.18), blend: 0.24),
            bloom: bloom(0.10, threshold: 0.76, radius: 18, softness: 0.78, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.26, radius: 0.94, softness: 0.92),
            lens: LensProfile(enabled: true, chromaticAberration: 0.14, edgeSoftness: 0.26, compactBlur: 0.04),
            dust: DustProfile(enabled: true, dustAmount: 0.20, scratchAmount: 0.12, lightLeakAmount: 0.12),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.42, edgeHaloSuppression: 0.38, localHDRCompression: 0.34, preBlur: 0.06),
            print: PrintResponseProfile(highlightDesaturation: 0.68, highlightRolloff: 0.68, paperBlack: 0.046, paperWhite: 0.936),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.10, crossProcess: 0.08, cyanShadow: 0.08, warmHighlight: 0.38, redChannelBloom: 0.06, greenBias: -0.03, blueBias: -0.08, dyeContamination: 0.34, scanFade: 0.46, cheapness: 0.24),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.76, dustJitter: 0.90, dateStampJitter: 0, flashJitter: 0)
        ),
        make(
            id: "kodak-funsaver-wedding",
            name: "Kodak FunSaver Wedding",
            description: "Built from wedding-table disposable references: forgiving 800-speed latitude, warm faces, soft plastic optics, and lively grain without a fake center flash.",
            exposure: 0.10, contrast: 1.08, toe: 0.36, shoulder: 0.74, black: 0.034, white: 0.925,
            saturation: 0.96, vibrance: 0.18, temp: 300, tint: -3,
            lut: "kodak-funsaver-800", lutIntensity: 0.90,
            grain: grain(.disposableCompact, size: 1.92, roughness: 0.82, strength: 0.34, chroma: 0.15, bias: 0.42, shadows: 0.88, mids: 1.22, highlights: 1.00, resolution: 0.48),
            halation: halation(0.16, threshold: 0.74, radius: 18, tint: CIColor(red: 1.0, green: 0.42, blue: 0.12), blend: 0.44),
            bloom: bloom(0.18, threshold: 0.70, radius: 18, softness: 0.80, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.32, radius: 0.88, softness: 0.94),
            lens: LensProfile(enabled: true, chromaticAberration: 0.56, edgeSoftness: 0.66, compactBlur: 0.18),
            dust: DustProfile(enabled: true, dustAmount: 0.060, scratchAmount: 0.012, lightLeakAmount: 0.040),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.56, edgeHaloSuppression: 0.62, localHDRCompression: 0.38, preBlur: 0.18),
            print: PrintResponseProfile(highlightDesaturation: 0.56, highlightRolloff: 0.74, paperBlack: 0.022, paperWhite: 0.968),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.34, crossProcess: 0.18, cyanShadow: 0.06, warmHighlight: 0.50, redChannelBloom: 0.34, greenBias: -0.02, blueBias: -0.08, dyeContamination: 0.34, scanFade: 0.10, cheapness: 0.54),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.38, dustJitter: 0.46, dateStampJitter: 0, flashJitter: 0),
            controls: controls(tone: 1.02, colour: 1.04, lut: 0.96, grain: 0.92, glow: 0.90, lens: 1.00, artefacts: 0.74)
        ),
        make(
            id: "kodak-funsaver-lowlight",
            name: "Kodak FunSaver Low Light",
            description: "Built from dark FunSaver party and venue samples: dense green-black shadows, warm skin lift, stronger rough grain, and compressed highlights.",
            exposure: -0.18, contrast: 1.36, toe: 0.18, shoulder: 0.78, black: 0.016, white: 0.900,
            saturation: 0.98, vibrance: 0.20, temp: 240, tint: -8,
            lut: "kodak-funsaver-800", lutIntensity: 0.98,
            grain: grain(.disposableCompact, size: 2.28, roughness: 0.94, strength: 0.48, chroma: 0.20, bias: 0.58, shadows: 1.28, mids: 1.46, highlights: 0.94, resolution: 0.36),
            halation: halation(0.28, threshold: 0.68, radius: 24, tint: CIColor(red: 1.0, green: 0.34, blue: 0.08), blend: 0.64),
            bloom: bloom(0.18, threshold: 0.72, radius: 22, softness: 0.80, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.48, radius: 0.78, softness: 0.96),
            lens: LensProfile(enabled: true, chromaticAberration: 0.84, edgeSoftness: 0.82, compactBlur: 0.28),
            dust: DustProfile(enabled: true, dustAmount: 0.090, scratchAmount: 0.018, lightLeakAmount: 0.070),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.68, edgeHaloSuppression: 0.76, localHDRCompression: 0.48, preBlur: 0.26),
            print: PrintResponseProfile(highlightDesaturation: 0.58, highlightRolloff: 0.82, paperBlack: 0.016, paperWhite: 0.940),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.50, crossProcess: 0.34, cyanShadow: 0.18, warmHighlight: 0.58, redChannelBloom: 0.54, greenBias: 0.08, blueBias: -0.10, dyeContamination: 0.54, scanFade: 0.02, cheapness: 0.82),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.58, dustJitter: 0.66, dateStampJitter: 0, flashJitter: 0),
            flatness: flatness(0.22, frequency: 0.72),
            labScan: labScan(0.18, noise: 0.10),
            controls: controls(tone: 1.04, colour: 1.08, lut: 1.04, grain: 1.08, glow: 1.06, lens: 1.08, artefacts: 0.82)
        ),
        make(
            id: "kodak-sun-haze",
            name: "Kodak Sun Haze",
            description: "Built from the high-luma outdoor FunSaver examples: pale warm highlights, dusty low saturation, big latitude, and soft edge haze.",
            exposure: 0.18, contrast: 0.98, toe: 0.44, shoulder: 0.86, black: 0.046, white: 0.890,
            saturation: 0.82, vibrance: 0.08, temp: 360, tint: -2,
            lut: "kodak-funsaver-800", lutIntensity: 0.82,
            grain: grain(.medium250, size: 1.76, roughness: 0.72, strength: 0.26, chroma: 0.10, bias: 0.34, shadows: 0.66, mids: 0.96, highlights: 1.08, resolution: 0.54),
            halation: halation(0.12, threshold: 0.76, radius: 22, tint: CIColor(red: 1.0, green: 0.48, blue: 0.18), blend: 0.38),
            bloom: bloom(0.24, threshold: 0.64, radius: 30, softness: 0.94, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.20, radius: 0.98, softness: 0.94),
            lens: LensProfile(enabled: true, chromaticAberration: 0.42, edgeSoftness: 0.64, compactBlur: 0.18),
            dust: DustProfile(enabled: true, dustAmount: 0.050, scratchAmount: 0.010, lightLeakAmount: 0.050),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.54, edgeHaloSuppression: 0.62, localHDRCompression: 0.54, preBlur: 0.20),
            print: PrintResponseProfile(highlightDesaturation: 0.76, highlightRolloff: 0.90, paperBlack: 0.030, paperWhite: 0.938),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.22, crossProcess: 0.12, cyanShadow: 0.04, warmHighlight: 0.58, redChannelBloom: 0.30, greenBias: -0.03, blueBias: -0.06, dyeContamination: 0.30, scanFade: 0.24, cheapness: 0.42),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.42, dustJitter: 0.40, dateStampJitter: 0, flashJitter: 0),
            controls: controls(tone: 1.08, colour: 0.96, lut: 0.90, grain: 0.82, glow: 1.10, lens: 0.94, artefacts: 0.68)
        ),
        make(
            id: "fuji-coastal-blue",
            name: "Fuji Coastal Blue",
            description: "Built from the tropical QuickSnap shoreline references: clear cyan sky, low warm bias, muted greens, clean grain, and soft plastic corners.",
            exposure: 0.18, contrast: 0.94, toe: 0.42, shoulder: 0.62, black: 0.040, white: 0.962,
            saturation: 0.92, vibrance: 0.20, temp: -560, tint: 0,
            lut: "fuji-quicksnap-400", lutIntensity: 0.90,
            grain: grain(.medium250, size: 1.34, roughness: 0.48, strength: 0.17, chroma: 0.09, bias: 0.38, shadows: 0.64, mids: 0.86, highlights: 0.56, resolution: 0.66),
            halation: halation(0.05, threshold: 0.86, radius: 12, tint: CIColor(red: 1.0, green: 0.42, blue: 0.20), blend: 0.18),
            bloom: bloom(0.08, threshold: 0.82, radius: 14, softness: 0.68, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.18, radius: 1.02, softness: 0.88),
            lens: LensProfile(enabled: true, chromaticAberration: 0.38, edgeSoftness: 0.74, compactBlur: 0.14),
            dust: DustProfile(enabled: true, dustAmount: 0.022, scratchAmount: 0.004, lightLeakAmount: 0.010),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.44, edgeHaloSuppression: 0.54, localHDRCompression: 0.42, preBlur: 0.14),
            print: PrintResponseProfile(highlightDesaturation: 0.50, highlightRolloff: 0.62, paperBlack: 0.024, paperWhite: 0.994),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.16, crossProcess: 0.06, cyanShadow: 0.42, warmHighlight: 0.06, redChannelBloom: 0.02, greenBias: 0.16, blueBias: 0.28, dyeContamination: 0.18, scanFade: 0.18, cheapness: 0.26),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.12, dustJitter: 0.18, dateStampJitter: 0, flashJitter: 0),
            controls: controls(tone: 1.00, colour: 1.08, lut: 0.96, grain: 0.74, glow: 0.58, lens: 0.94, artefacts: 0.42)
        ),
        make(
            id: "fuji-selfie-print",
            name: "Fuji Selfie Print",
            description: "Built from Fuji/simple-ace comparison selfies: bright faces, cool shadows, restrained saturation, and compact-camera softness without radial flash whitening.",
            exposure: 0.24, contrast: 0.88, toe: 0.48, shoulder: 0.78, black: 0.052, white: 0.940,
            saturation: 0.82, vibrance: 0.16, temp: -260, tint: -6,
            lut: "fuji-quicksnap-400", lutIntensity: 0.78,
            grain: grain(.fine50, size: 1.20, roughness: 0.42, strength: 0.14, chroma: 0.08, bias: 0.34, shadows: 0.56, mids: 0.78, highlights: 0.52, resolution: 0.68),
            halation: halation(0.04, threshold: 0.86, radius: 10, tint: CIColor(red: 1.0, green: 0.44, blue: 0.20), blend: 0.16),
            bloom: bloom(0.16, threshold: 0.66, radius: 24, softness: 0.92, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.16, radius: 1.05, softness: 0.90),
            lens: LensProfile(enabled: true, chromaticAberration: 0.30, edgeSoftness: 0.58, compactBlur: 0.16),
            dust: DustProfile(enabled: true, dustAmount: 0.018, scratchAmount: 0.002, lightLeakAmount: 0.008),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.52, edgeHaloSuppression: 0.58, localHDRCompression: 0.50, preBlur: 0.18),
            print: PrintResponseProfile(highlightDesaturation: 0.66, highlightRolloff: 0.78, paperBlack: 0.030, paperWhite: 0.976),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.10, crossProcess: 0.04, cyanShadow: 0.26, warmHighlight: 0.12, redChannelBloom: 0.04, greenBias: 0.10, blueBias: 0.12, dyeContamination: 0.12, scanFade: 0.30, cheapness: 0.20),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.08, dustJitter: 0.14, dateStampJitter: 0, flashJitter: 0),
            controls: controls(tone: 1.04, colour: 0.98, lut: 0.86, grain: 0.64, glow: 0.86, lens: 0.82, artefacts: 0.30)
        ),
        make(
            id: "huji-red-leak",
            name: "HUJI Red Leak",
            description: "Built from HUJI app-screen and light-leak references: saturated orange edge leak, crunchy date-stamped processing, clipped reds, and heavy phone-detail taming.",
            exposure: -0.02, contrast: 1.28, toe: 0.20, shoulder: 0.82, black: 0.024, white: 0.892,
            saturation: 1.16, vibrance: 0.42, temp: 500, tint: -12,
            lut: "huji-flash-leak", lutIntensity: 1.0,
            grain: grain(.disposableCompact, size: 2.18, roughness: 0.94, strength: 0.42, chroma: 0.40, bias: 0.42, shadows: 1.08, mids: 1.50, highlights: 0.86, resolution: 0.38),
            halation: halation(0.42, threshold: 0.64, radius: 30, tint: CIColor(red: 1.0, green: 0.25, blue: 0.04), blend: 0.84),
            bloom: bloom(0.28, threshold: 0.64, radius: 28, softness: 0.92, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.42, radius: 0.78, softness: 0.94),
            lens: LensProfile(enabled: true, chromaticAberration: 1.10, edgeSoftness: 0.82, compactBlur: 0.28),
            dust: DustProfile(enabled: true, dustAmount: 0.120, scratchAmount: 0.034, lightLeakAmount: 0.68),
            stamp: DateStampProfile(enabled: true, text: DateFormatter.filmStamp.string(from: Date()), opacity: 1.0),
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.72, edgeHaloSuppression: 0.80, localHDRCompression: 0.56, preBlur: 0.28),
            print: PrintResponseProfile(highlightDesaturation: 0.62, highlightRolloff: 0.84, paperBlack: 0.018, paperWhite: 0.944),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.92, crossProcess: 0.72, cyanShadow: 0.16, warmHighlight: 0.84, redChannelBloom: 0.86, greenBias: -0.10, blueBias: -0.16, dyeContamination: 0.82, scanFade: 0.02, cheapness: 1.08),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 1.70, dustJitter: 1.05, dateStampJitter: 1.20, flashJitter: 0),
            controls: controls(tone: 1.02, colour: 1.12, lut: 1.08, grain: 1.02, glow: 1.14, lens: 1.08, artefacts: 1.28)
        ),
        make(
            id: "huji-alley-green",
            name: "HUJI Alley Green",
            description: "Built from darker HUJI boards and low-light disposable examples: deep shadow pressure, green-cyan blacks, orange highs, and coarse app-camera artifacts.",
            exposure: -0.28, contrast: 1.40, toe: 0.14, shoulder: 0.72, black: 0.014, white: 0.902,
            saturation: 0.96, vibrance: 0.26, temp: 80, tint: -12,
            lut: "huji-1998", lutIntensity: 0.96,
            grain: grain(.disposableCompact, size: 2.26, roughness: 0.92, strength: 0.44, chroma: 0.30, bias: 0.60, shadows: 1.34, mids: 1.46, highlights: 0.70, resolution: 0.36),
            halation: halation(0.30, threshold: 0.66, radius: 25, tint: CIColor(red: 1.0, green: 0.30, blue: 0.06), blend: 0.72),
            bloom: bloom(0.18, threshold: 0.72, radius: 20, softness: 0.82, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.54, radius: 0.72, softness: 0.98),
            lens: LensProfile(enabled: true, chromaticAberration: 1.04, edgeSoftness: 0.88, compactBlur: 0.30),
            dust: DustProfile(enabled: true, dustAmount: 0.110, scratchAmount: 0.028, lightLeakAmount: 0.22),
            stamp: DateStampProfile(enabled: true, text: DateFormatter.filmStamp.string(from: Date()), opacity: 0.96),
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.74, edgeHaloSuppression: 0.80, localHDRCompression: 0.56, preBlur: 0.30),
            print: PrintResponseProfile(highlightDesaturation: 0.58, highlightRolloff: 0.78, paperBlack: 0.014, paperWhite: 0.946),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.82, crossProcess: 0.62, cyanShadow: 0.34, warmHighlight: 0.64, redChannelBloom: 0.64, greenBias: 0.12, blueBias: -0.02, dyeContamination: 0.72, scanFade: 0.00, cheapness: 1.02),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 1.18, dustJitter: 0.90, dateStampJitter: 1.10, flashJitter: 0),
            controls: controls(tone: 1.06, colour: 1.08, lut: 1.00, grain: 1.08, glow: 1.02, lens: 1.10, artefacts: 0.96)
        ),
        make(
            id: "huji-date-night",
            name: "HUJI Date Night",
            description: "Built from HUJI direct night/casual frames: dark average luma, warm red highlights, visible grain, date stamp, and moderate randomized defects.",
            exposure: -0.12, contrast: 1.18, toe: 0.24, shoulder: 0.72, black: 0.024, white: 0.916,
            saturation: 1.08, vibrance: 0.34, temp: 360, tint: -8,
            lut: "huji-1998", lutIntensity: 0.92,
            grain: grain(.disposableCompact, size: 2.00, roughness: 0.84, strength: 0.34, chroma: 0.28, bias: 0.48, shadows: 0.98, mids: 1.28, highlights: 0.76, resolution: 0.46),
            halation: halation(0.30, threshold: 0.68, radius: 24, tint: CIColor(red: 1.0, green: 0.32, blue: 0.07), blend: 0.68),
            bloom: bloom(0.18, threshold: 0.70, radius: 22, softness: 0.84, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.40, radius: 0.82, softness: 0.94),
            lens: LensProfile(enabled: true, chromaticAberration: 0.86, edgeSoftness: 0.74, compactBlur: 0.24),
            dust: DustProfile(enabled: true, dustAmount: 0.085, scratchAmount: 0.020, lightLeakAmount: 0.18),
            stamp: DateStampProfile(enabled: true, text: DateFormatter.filmStamp.string(from: Date()), opacity: 0.92),
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.66, edgeHaloSuppression: 0.74, localHDRCompression: 0.48, preBlur: 0.24),
            print: PrintResponseProfile(highlightDesaturation: 0.54, highlightRolloff: 0.76, paperBlack: 0.020, paperWhite: 0.954),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.66, crossProcess: 0.50, cyanShadow: 0.16, warmHighlight: 0.62, redChannelBloom: 0.58, greenBias: -0.04, blueBias: -0.08, dyeContamination: 0.58, scanFade: 0.06, cheapness: 0.78),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.88, dustJitter: 0.72, dateStampJitter: 0.96, flashJitter: 0),
            controls: controls(tone: 1.00, colour: 1.06, lut: 0.96, grain: 0.94, glow: 1.04, lens: 1.00, artefacts: 0.88)
        ),
        make(
            id: "dazz-classic-room",
            name: "Dazz Classic Room",
            description: "Built from Dazz Classic interior references: warm room light, low saturation, lifted blacks, gentle organic softness, and restrained defects.",
            exposure: 0.04, contrast: 0.92, toe: 0.48, shoulder: 0.64, black: 0.054, white: 0.944,
            saturation: 0.86, vibrance: 0.16, temp: 300, tint: 2,
            lut: "dazz-classic", lutIntensity: 0.84,
            grain: grain(.fine50, size: 1.22, roughness: 0.48, strength: 0.14, chroma: 0.08, bias: 0.54, shadows: 0.58, mids: 0.86, highlights: 0.54, resolution: 0.76),
            halation: halation(0.10, threshold: 0.82, radius: 15, tint: CIColor(red: 1.0, green: 0.44, blue: 0.18), blend: 0.30),
            bloom: bloom(0.16, threshold: 0.72, radius: 22, softness: 0.88, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.14, radius: 1.10, softness: 0.86),
            lens: LensProfile(enabled: true, chromaticAberration: 0.22, edgeSoftness: 0.32, compactBlur: 0.08),
            dust: DustProfile(enabled: true, dustAmount: 0.030, scratchAmount: 0.006, lightLeakAmount: 0.025),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.44, edgeHaloSuppression: 0.46, localHDRCompression: 0.38, preBlur: 0.10),
            print: PrintResponseProfile(highlightDesaturation: 0.48, highlightRolloff: 0.64, paperBlack: 0.032, paperWhite: 0.980),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.20, crossProcess: 0.10, cyanShadow: 0.08, warmHighlight: 0.32, redChannelBloom: 0.10, greenBias: -0.02, blueBias: -0.02, dyeContamination: 0.20, scanFade: 0.26, cheapness: 0.10),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.22, dustJitter: 0.20, dateStampJitter: 0, flashJitter: 0),
            controls: controls(tone: 0.96, colour: 0.98, lut: 0.92, grain: 0.76, glow: 0.82, lens: 0.76, artefacts: 0.48)
        ),
        make(
            id: "dazz-dfuns-market",
            name: "Dazz DFuns Market",
            description: "Built from the Dazz market/night references: low luma, high warm bias, red-orange mids, visible grain proxy, and casual app-camera glow.",
            exposure: -0.20, contrast: 1.16, toe: 0.28, shoulder: 0.68, black: 0.022, white: 0.924,
            saturation: 1.24, vibrance: 0.34, temp: 520, tint: -4,
            lut: "dazz-d-exp", lutIntensity: 0.90,
            grain: grain(.medium250, size: 1.56, roughness: 0.70, strength: 0.27, chroma: 0.18, bias: 0.62, shadows: 0.96, mids: 1.22, highlights: 0.88, resolution: 0.60),
            halation: halation(0.28, threshold: 0.68, radius: 25, tint: CIColor(red: 1.0, green: 0.30, blue: 0.06), blend: 0.64),
            bloom: bloom(0.22, threshold: 0.68, radius: 24, softness: 0.86, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.32, radius: 0.88, softness: 0.90),
            lens: LensProfile(enabled: true, chromaticAberration: 0.48, edgeSoftness: 0.46, compactBlur: 0.10),
            dust: DustProfile(enabled: true, dustAmount: 0.060, scratchAmount: 0.012, lightLeakAmount: 0.070),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.48, edgeHaloSuppression: 0.52, localHDRCompression: 0.36, preBlur: 0.12),
            print: PrintResponseProfile(highlightDesaturation: 0.40, highlightRolloff: 0.68, paperBlack: 0.018, paperWhite: 0.968),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.46, crossProcess: 0.34, cyanShadow: 0.16, warmHighlight: 0.58, redChannelBloom: 0.40, greenBias: -0.04, blueBias: -0.08, dyeContamination: 0.40, scanFade: 0.10, cheapness: 0.26),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.50, dustJitter: 0.34, dateStampJitter: 0, flashJitter: 0),
            controls: controls(tone: 1.02, colour: 1.12, lut: 0.98, grain: 0.98, glow: 1.06, lens: 0.90, artefacts: 0.72)
        ),
        make(
            id: "dazz-soft-portrait",
            name: "Dazz Soft Portrait",
            description: "Built from Dazz portrait/filter references: creamy high-key scan fade, low grain, pastel skin, softened phone sharpness, and mild bloom.",
            exposure: 0.14, contrast: 0.82, toe: 0.58, shoulder: 0.76, black: 0.066, white: 0.928,
            saturation: 0.80, vibrance: 0.14, temp: 220, tint: 4,
            lut: "dazz-cpm35", lutIntensity: 0.86,
            grain: grain(.fine50, size: 1.00, roughness: 0.34, strength: 0.07, chroma: 0.04, bias: 0.44, shadows: 0.42, mids: 0.60, highlights: 0.38, resolution: 0.88),
            halation: halation(0.06, threshold: 0.86, radius: 13, tint: CIColor(red: 1.0, green: 0.48, blue: 0.24), blend: 0.22),
            bloom: bloom(0.24, threshold: 0.64, radius: 30, softness: 0.96, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.08, radius: 1.24, softness: 0.84),
            lens: LensProfile(enabled: true, chromaticAberration: 0.12, edgeSoftness: 0.22, compactBlur: 0.10),
            dust: DustProfile(enabled: true, dustAmount: 0.014, scratchAmount: 0.002, lightLeakAmount: 0.008),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.52, edgeHaloSuppression: 0.44, localHDRCompression: 0.48, preBlur: 0.14),
            print: PrintResponseProfile(highlightDesaturation: 0.66, highlightRolloff: 0.74, paperBlack: 0.036, paperWhite: 0.990),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.08, crossProcess: 0.02, cyanShadow: 0.06, warmHighlight: 0.22, redChannelBloom: 0.04, greenBias: -0.02, blueBias: 0.02, dyeContamination: 0.10, scanFade: 0.42, cheapness: 0.00),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.08, dustJitter: 0.08, dateStampJitter: 0, flashJitter: 0),
            controls: controls(tone: 0.98, colour: 0.94, lut: 0.92, grain: 0.52, glow: 1.02, lens: 0.58, artefacts: 0.24)
        ),
        make(
            id: "dazz-parallax-dark",
            name: "Dazz Parallax Dark",
            description: "Built from the darkest Dazz comparison frames: crushed shadows, restrained chroma, sharper app contrast, small grain, and cool shadow contamination.",
            exposure: -0.24, contrast: 1.36, toe: 0.18, shoulder: 0.54, black: 0.012, white: 0.948,
            saturation: 0.92, vibrance: 0.10, temp: 80, tint: -4,
            lut: "dazz-d-exp", lutIntensity: 0.96,
            grain: grain(.fine50, size: 1.18, roughness: 0.52, strength: 0.18, chroma: 0.08, bias: 0.60, shadows: 0.92, mids: 0.98, highlights: 0.56, resolution: 0.72),
            halation: halation(0.14, threshold: 0.78, radius: 16, tint: CIColor(red: 1.0, green: 0.32, blue: 0.10), blend: 0.38),
            bloom: bloom(0.08, threshold: 0.82, radius: 12, softness: 0.58, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.30, radius: 0.92, softness: 0.84),
            lens: LensProfile(enabled: true, chromaticAberration: 0.38, edgeSoftness: 0.28, compactBlur: 0.04),
            dust: DustProfile(enabled: true, dustAmount: 0.030, scratchAmount: 0.006, lightLeakAmount: 0.025),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.30, edgeHaloSuppression: 0.36, localHDRCompression: 0.16, preBlur: 0.04),
            print: PrintResponseProfile(highlightDesaturation: 0.22, highlightRolloff: 0.44, paperBlack: 0.006, paperWhite: 0.992),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.58, crossProcess: 0.38, cyanShadow: 0.28, warmHighlight: 0.24, redChannelBloom: 0.16, greenBias: 0.04, blueBias: 0.08, dyeContamination: 0.30, scanFade: -0.04, cheapness: 0.08),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.18, dustJitter: 0.18, dateStampJitter: 0, flashJitter: 0),
            controls: controls(tone: 1.04, colour: 1.00, lut: 1.02, grain: 0.76, glow: 0.72, lens: 0.72, artefacts: 0.48)
        ),

        // MARK: Push/Pull Variants
        make(
            id: "kodak-funsaver-800-p1",
            name: "Kodak FunSaver 800 +1 Push",
            description: "Kodak FunSaver pushed +1 stop: increased grain RMS, crushed blacks, elevated green shadow tint, boosted color separation.",
            exposure: 0.03, contrast: 1.30, toe: 0.28, shoulder: 0.76, black: 0.024, white: 0.905,
            saturation: 0.94, vibrance: 0.12, temp: 260, tint: -4,
            lut: "kodak-funsaver-800", lutIntensity: 0.96,
            grain: grain(.disposableCompact, size: 2.12, roughness: 0.90, strength: 0.44, chroma: 0.18, bias: 0.42, shadows: 1.06, mids: 1.42, highlights: 1.12, resolution: 0.42),
            halation: halation(0.22, threshold: 0.72, radius: 18, tint: CIColor(red: 1.0, green: 0.40, blue: 0.10), blend: 0.54),
            bloom: bloom(0.14, threshold: 0.75, radius: 14, softness: 0.70, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.40, radius: 0.82, softness: 0.92),
            lens: LensProfile(enabled: true, chromaticAberration: 0.72, edgeSoftness: 0.76, compactBlur: 0.22),
            dust: DustProfile(enabled: true, dustAmount: 0.080, scratchAmount: 0.018, lightLeakAmount: 0.045),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.60, edgeHaloSuppression: 0.68, localHDRCompression: 0.36, preBlur: 0.22),
            print: PrintResponseProfile(highlightDesaturation: 0.58, highlightRolloff: 0.76, paperBlack: 0.018, paperWhite: 0.958),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.42, crossProcess: 0.26, cyanShadow: 0.08, warmHighlight: 0.52, redChannelBloom: 0.42, greenBias: -0.02, blueBias: -0.08, dyeContamination: 0.44, scanFade: 0.06, cheapness: 0.70),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.42, dustJitter: 0.56, dateStampJitter: 0, flashJitter: 0),
            flatness: flatness(0.16, frequency: 0.85),
            labScan: labScan(0.14, noise: 0.06),
            pushPull: 1,
            controls: controls(tone: 1.02, colour: 1.06, lut: 0.96, grain: 1.04, glow: 0.92, lens: 1.00, artefacts: 0.74)
        ),
        make(
            id: "huji-direct-p1",
            name: "HUJI Direct +1 Push",
            description: "HUJI Direct pushed +1 stop: crunchy contrast, boosted grain, green shadow lift, aggressive color separation.",
            exposure: -0.10, contrast: 1.24, toe: 0.20, shoulder: 0.70, black: 0.028, white: 0.910,
            saturation: 1.04, vibrance: 0.30, temp: 320, tint: -8,
            lut: "huji-1998", lutIntensity: 0.96,
            grain: grain(.disposableCompact, size: 1.92, roughness: 0.84, strength: 0.36, chroma: 0.32, bias: 0.40, shadows: 1.00, mids: 1.36, highlights: 0.78, resolution: 0.46),
            halation: halation(0.28, threshold: 0.68, radius: 23, tint: CIColor(red: 1.0, green: 0.32, blue: 0.07), blend: 0.66),
            bloom: bloom(0.20, threshold: 0.70, radius: 21, softness: 0.84, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.38, radius: 0.82, softness: 0.94),
            lens: LensProfile(enabled: true, chromaticAberration: 0.94, edgeSoftness: 0.72, compactBlur: 0.24),
            dust: DustProfile(enabled: true, dustAmount: 0.100, scratchAmount: 0.028, lightLeakAmount: 0.22),
            stamp: DateStampProfile(enabled: true, text: DateFormatter.filmStamp.string(from: Date()), opacity: 0.92),
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.66, edgeHaloSuppression: 0.74, localHDRCompression: 0.50, preBlur: 0.24),
            print: PrintResponseProfile(highlightDesaturation: 0.56, highlightRolloff: 0.76, paperBlack: 0.020, paperWhite: 0.958),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.74, crossProcess: 0.54, cyanShadow: 0.18, warmHighlight: 0.66, redChannelBloom: 0.60, greenBias: -0.06, blueBias: -0.08, dyeContamination: 0.62, scanFade: 0.06, cheapness: 0.88),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 1.12, dustJitter: 0.84, dateStampJitter: 1.00, flashJitter: 0),
            flatness: flatness(0.22, frequency: 0.72),
            labScan: labScan(0.20, noise: 0.12),
            pushPull: 1,
            controls: controls(tone: 1.02, colour: 1.08, lut: 0.96, grain: 1.06, glow: 1.00, lens: 1.02, artefacts: 0.88)
        ),
        make(
            id: "dazz-night-market-p1",
            name: "Dazz Night Market +1 Push",
            description: "Dazz Night Market pushed +1 stop: extreme contrast, pumped grain, warm color separation, crushed blacks.",
            exposure: -0.16, contrast: 1.12, toe: 0.30, shoulder: 0.66, black: 0.024, white: 0.930,
            saturation: 1.18, vibrance: 0.28, temp: 420, tint: -2,
            lut: "dazz-d-exp", lutIntensity: 0.86,
            grain: grain(.medium250, size: 1.56, roughness: 0.70, strength: 0.27, chroma: 0.18, bias: 0.62, shadows: 0.96, mids: 1.22, highlights: 0.88, resolution: 0.60),
            halation: halation(0.28, threshold: 0.68, radius: 25, tint: CIColor(red: 1.0, green: 0.30, blue: 0.06), blend: 0.64),
            bloom: bloom(0.22, threshold: 0.68, radius: 24, softness: 0.86, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.32, radius: 0.88, softness: 0.90),
            lens: LensProfile(enabled: true, chromaticAberration: 0.48, edgeSoftness: 0.46, compactBlur: 0.10),
            dust: DustProfile(enabled: true, dustAmount: 0.060, scratchAmount: 0.012, lightLeakAmount: 0.070),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.48, edgeHaloSuppression: 0.52, localHDRCompression: 0.36, preBlur: 0.12),
            print: PrintResponseProfile(highlightDesaturation: 0.40, highlightRolloff: 0.68, paperBlack: 0.018, paperWhite: 0.968),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.46, crossProcess: 0.34, cyanShadow: 0.16, warmHighlight: 0.58, redChannelBloom: 0.40, greenBias: -0.04, blueBias: -0.08, dyeContamination: 0.40, scanFade: 0.10, cheapness: 0.26),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.50, dustJitter: 0.34, dateStampJitter: 0, flashJitter: 0),
            pushPull: 1,
            controls: controls(tone: 1.02, colour: 1.10, lut: 0.98, grain: 1.04, glow: 1.06, lens: 0.90, artefacts: 0.72)
        ),

        // MARK: X-Pro (Cross-Processing) Presets
        make(
            id: "xpro-kodak-c41",
            name: "X-Pro Kodak C-41",
            description: "Cross-processed: Kodak slide film developed in C-41 chemicals. Wild contrast, cyan-green shadows, golden highlights.",
            exposure: -0.06, contrast: 1.32, toe: 0.24, shoulder: 0.64, black: 0.018, white: 0.944,
            saturation: 1.28, vibrance: 0.36, temp: 180, tint: -4,
            lut: "kodak-funsaver-800", lutIntensity: 0.70,
            grain: grain(.disposableCompact, size: 1.88, roughness: 0.74, strength: 0.28, chroma: 0.22, bias: 0.48, shadows: 0.92, mids: 1.18, highlights: 0.76, resolution: 0.52),
            halation: halation(0.14, threshold: 0.76, radius: 15, tint: CIColor(red: 1.0, green: 0.35, blue: 0.08), blend: 0.42),
            bloom: bloom(0.12, threshold: 0.74, radius: 16, softness: 0.72, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.28, radius: 0.90, softness: 0.88),
            lens: LensProfile(enabled: true, chromaticAberration: 0.44, edgeSoftness: 0.52, compactBlur: 0.14),
            dust: DustProfile(enabled: true, dustAmount: 0.060, scratchAmount: 0.012, lightLeakAmount: 0.030),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.44, edgeHaloSuppression: 0.52, localHDRCompression: 0.40, preBlur: 0.14),
            print: PrintResponseProfile(highlightDesaturation: 0.42, highlightRolloff: 0.60, paperBlack: 0.014, paperWhite: 0.982),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.62, crossProcess: 0.74, cyanShadow: 0.22, warmHighlight: 0.48, redChannelBloom: 0.56, greenBias: -0.04, blueBias: 0.06, dyeContamination: 0.52, scanFade: 0.04, cheapness: 0.44),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.30, dustJitter: 0.40, dateStampJitter: 0, flashJitter: 0)
        ),
        make(
            id: "xpro-fuji-c41",
            name: "X-Pro Fuji C-41",
            description: "Cross-processed: Fuji slide film in C-41. Cyan-teal shadow cast, magenta-gold crossover, extreme saturation.",
            exposure: 0.02, contrast: 1.22, toe: 0.30, shoulder: 0.58, black: 0.026, white: 0.952,
            saturation: 1.34, vibrance: 0.40, temp: -160, tint: -8,
            lut: "fuji-quicksnap-400", lutIntensity: 0.62,
            grain: grain(.medium250, size: 1.34, roughness: 0.54, strength: 0.18, chroma: 0.16, bias: 0.44, shadows: 0.72, mids: 0.96, highlights: 0.62, resolution: 0.60),
            halation: halation(0.10, threshold: 0.78, radius: 14, tint: CIColor(red: 1.0, green: 0.42, blue: 0.14), blend: 0.36),
            bloom: bloom(0.14, threshold: 0.74, radius: 18, softness: 0.76, mode: .softLight),
            vignette: VignetteProfile(enabled: true, intensity: 0.22, radius: 0.94, softness: 0.86),
            lens: LensProfile(enabled: true, chromaticAberration: 0.52, edgeSoftness: 0.62, compactBlur: 0.12),
            dust: DustProfile(enabled: true, dustAmount: 0.040, scratchAmount: 0.008, lightLeakAmount: 0.025),
            stamp: .none,
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.48, edgeHaloSuppression: 0.56, localHDRCompression: 0.44, preBlur: 0.16),
            print: PrintResponseProfile(highlightDesaturation: 0.46, highlightRolloff: 0.56, paperBlack: 0.020, paperWhite: 0.988),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.48, crossProcess: 0.68, cyanShadow: 0.32, warmHighlight: 0.36, redChannelBloom: 0.40, greenBias: 0.08, blueBias: 0.12, dyeContamination: 0.44, scanFade: 0.08, cheapness: 0.32),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.26, dustJitter: 0.30, dateStampJitter: 0, flashJitter: 0)
        ),
        make(
            id: "xpro-huji-c41",
            name: "X-Pro HUJI C-41",
            description: "Cross-processed HUJI: slide film in C-41 with app-grade artifacts. Deep teal shadows, neon gold highlights, heavy grain.",
            exposure: -0.14, contrast: 1.40, toe: 0.18, shoulder: 0.70, black: 0.014, white: 0.920,
            saturation: 1.42, vibrance: 0.46, temp: 120, tint: -10,
            lut: "huji-1998", lutIntensity: 0.58,
            grain: grain(.disposableCompact, size: 2.02, roughness: 0.80, strength: 0.34, chroma: 0.30, bias: 0.52, shadows: 1.02, mids: 1.28, highlights: 0.72, resolution: 0.44),
            halation: halation(0.18, threshold: 0.72, radius: 20, tint: CIColor(red: 1.0, green: 0.30, blue: 0.05), blend: 0.52),
            bloom: bloom(0.16, threshold: 0.72, radius: 18, softness: 0.80, mode: .screen),
            vignette: VignetteProfile(enabled: true, intensity: 0.32, radius: 0.88, softness: 0.90),
            lens: LensProfile(enabled: true, chromaticAberration: 0.70, edgeSoftness: 0.64, compactBlur: 0.20),
            dust: DustProfile(enabled: true, dustAmount: 0.075, scratchAmount: 0.016, lightLeakAmount: 0.40),
            stamp: DateStampProfile(enabled: true, text: DateFormatter.filmStamp.string(from: Date()), opacity: 0.80),
            taming: DigitalTamingProfile(enabled: true, clarityReduction: 0.60, edgeHaloSuppression: 0.68, localHDRCompression: 0.46, preBlur: 0.22),
            print: PrintResponseProfile(highlightDesaturation: 0.38, highlightRolloff: 0.64, paperBlack: 0.012, paperWhite: 0.966),
            response: CameraResponseProfile(enabled: true, colorSeparation: 0.78, crossProcess: 0.82, cyanShadow: 0.28, warmHighlight: 0.60, redChannelBloom: 0.70, greenBias: -0.08, blueBias: 0.10, dyeContamination: 0.62, scanFade: 0.02, cheapness: 0.60),
            randomness: RandomnessProfile(enabled: true, lightLeakJitter: 0.80, dustJitter: 0.64, dateStampJitter: 0.80, flashJitter: 0)
        )
    ]

    private static func make(
        id: String,
        name: String,
        description: String,
        exposure: Double,
        contrast: Double,
        toe: Double,
        shoulder: Double,
        black: Double,
        white: Double,
        saturation: Double,
        vibrance: Double,
        temp: Double,
        tint: Double,
        lut: String,
        lutIntensity: Double,
        grain: GrainProfile,
        halation: HalationProfile,
        bloom: BloomProfile,
        vignette: VignetteProfile,
        lens: LensProfile,
        dust: DustProfile,
        stamp: DateStampProfile,
        taming: DigitalTamingProfile,
        print: PrintResponseProfile,
        response: CameraResponseProfile,
        randomness: RandomnessProfile,
        flatness: FilmFlatnessProfile = .none,
        labScan: LabScanProfile = .none,
        pushPull: Double = 0,
        controls: LookComponentIntensities = .standard
    ) -> FilmLookProfile {
        FilmLookProfile(
            id: id,
            name: name,
            description: description,
            baseExposure: exposure,
            contrast: contrast,
            toeStrength: toe,
            shoulderStrength: shoulder,
            blackPoint: black,
            whitePoint: white,
            saturation: saturation,
            vibrance: vibrance,
            colourTemperatureBias: temp,
            tintBias: tint,
            digitalTamingProfile: taming,
            printProfile: print,
            cameraResponseProfile: response,
            lutName: lut,
            lutURL: nil,
            lutIntensity: lutIntensity,
            grainProfile: grain,
            halationProfile: halation,
            bloomProfile: bloom,
            vignetteProfile: vignette,
            lensProfile: lens,
            dustProfile: dust,
            dateStampProfile: stamp,
            randomnessProfile: randomness,
            filmFlatnessProfile: flatness,
            labScanProfile: labScan,
            pushPull: pushPull,
            componentDefaults: controls
        )
    }

    private static func controls(
        tone: Double = 1,
        colour: Double = 1,
        lut: Double = 1,
        grain: Double = 1,
        glow: Double = 1,
        lens: Double = 1,
        artefacts: Double = 1,
        softness: Double = 1
    ) -> LookComponentIntensities {
        LookComponentIntensities(
            tone: tone,
            colour: colour,
            lut: lut,
            grain: grain,
            glow: glow,
            lens: lens,
            artefacts: artefacts,
            softness: softness
        )
    }

    private static func grain(
        _ preset: GrainPreset,
        size: Double,
        roughness: Double,
        strength: Double,
        chroma: Double,
        bias: Double,
        shadows: Double,
        mids: Double,
        highlights: Double,
        resolution: Double
    ) -> GrainProfile {
        // Recalibrated for pure density-domain model (no additive overlay pass).
        // Density-only grain is ~1.6x more subtle than additive, so boost accordingly.
        GrainProfile(
            enabled: true,
            preset: preset,
            size: size,
            roughness: roughness,
            strength: strength * 1.6,
            chromaAmount: chroma,
            highlightBias: bias,
            shadowAmount: shadows,
            midtoneAmount: mids,
            highlightAmount: highlights,
            resolution: resolution
        )
    }

    private static func halation(_ intensity: Double, threshold: Double, radius: Double, tint: CIColor, blend: Double) -> HalationProfile {
        HalationProfile(enabled: true, intensity: intensity, threshold: threshold, radius: radius, tint: tint, blend: blend)
    }

    private static func bloom(_ intensity: Double, threshold: Double, radius: Double, softness: Double, mode: BloomBlendMode) -> BloomProfile {
        BloomProfile(enabled: true, threshold: threshold, radius: radius, intensity: intensity, softness: softness, blendMode: mode)
    }

    private static func flatness(_ intensity: Double, frequency: Double = 1) -> FilmFlatnessProfile {
        FilmFlatnessProfile(enabled: true, intensity: intensity, frequency: frequency)
    }

    private static func labScan(_ shadowShift: Double, noise: Double = 0) -> LabScanProfile {
        LabScanProfile(enabled: true, shadowColorShift: shadowShift, scannerNoiseAmount: noise)
    }
}

private extension DateFormatter {
    static let filmStamp: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "yy  MM  dd"
        return formatter
    }()
}
